title: 'Prueba_Sena '
description: Subir prueba
template:
  repo: prueba_sena-template
  name: prueba_sena
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
